# Generated by Django 3.0.4 on 2020-03-20 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball_key', models.CharField(max_length=8)),
                ('innings_number', models.IntegerField()),
                ('over_number', models.IntegerField()),
                ('ball_number', models.IntegerField()),
                ('runs', models.IntegerField()),
                ('bat_runs', models.IntegerField()),
                ('extra_runs', models.IntegerField()),
                ('wides', models.IntegerField()),
                ('noballs', models.IntegerField()),
                ('byes', models.IntegerField()),
                ('leg_byes', models.IntegerField()),
                ('is_wicket', models.BooleanField()),
                ('how_out', models.IntegerField()),
                ('total_balls', models.IntegerField()),
                ('total_bowler_balls', models.IntegerField()),
                ('total_batsman_balls', models.IntegerField()),
                ('total_runs', models.IntegerField()),
                ('total_bat_runs', models.IntegerField()),
                ('total_extra_runs', models.IntegerField()),
                ('total_wickets', models.IntegerField()),
                ('total_bowler_wickets', models.IntegerField()),
                ('wagon_x', models.FloatField()),
                ('wagon_y', models.FloatField()),
                ('batsman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batsman', to='core.Player')),
                ('bowler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowler', to='core.Player')),
                ('fielder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fielder', to='core.Player')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='core.Match')),
                ('non_striker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_striker', to='core.Player')),
                ('out_batsman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_batsman', to='core.Player')),
            ],
        ),
    ]
