# Generated by Django 3.0.4 on 2020-04-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcsp_bbb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ball',
            name='total_bowl_runs',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
