# Generated by Django 3.0.4 on 2020-04-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcsp_bbb', '0002_ball_total_bowl_runs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ball',
            name='how_out',
            field=models.CharField(max_length=20),
        ),
    ]
