# Generated by Django 3.0.4 on 2020-04-11 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('pcsp_bbb', '0003_auto_20200411_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ball',
            name='fielder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fielder', to='core.Player'),
        ),
        migrations.AlterField(
            model_name='ball',
            name='out_batsman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='out_batsman', to='core.Player'),
        ),
    ]
