# Generated by Django 3.0.4 on 2020-04-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcsp_bbb', '0004_auto_20200411_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ball',
            name='wagon_x',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ball',
            name='wagon_y',
            field=models.FloatField(null=True),
        ),
    ]
