# Generated by Django 3.0.4 on 2020-04-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcsp_bbb', '0006_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_error',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
