# Generated by Django 3.0.4 on 2020-04-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcsp_bbb', '0007_match_is_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='is_error',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='is_pcsp',
            field=models.BooleanField(default=False),
        ),
    ]
